"""This module contains string constants for Armor Sets locations"""

class RACSMTARMORSET:
    """String constants for Armor Set locations"""
    CHAMELEON = "Armor Set: Equip Chameleon Armor Set"
    CRYSTALLIX = "Armor Set: Equip Crystallix Armor Set"
    ELECTROSHOCK = "Armor Set: Equip Electroshock Armor Set"
    FIRE_BOMB = "Armor Set: Equip Fire-Bomb Armor Set"
    HYPERBOREAN = "Armor Set: Equip Hyperborean Armor Set"
    ICE_II = "Armor Set: Equip Ice II Armor Set"
    MEGA_BOMB = "Armor Set: Equip Mega Bomb Armor Set"
    SHOCK_CRYSTAL = "Armor Set: Equip Shock Crystal Armor Set"
    SLUDGE_MK9 = "Armor Set: Equip Sludge Mk9 Armor Set"
    STALKER = "Armor Set: Equip Stalker Armor Set"
    TRIPLE_WAVE = "Armor Set: Equip Triple Wave Armor Set"
    WILDBURST = "Armor Set: Equip Wildburst Armor Set"
    WILDFIRE = "Armor Set: Equip Wildfire Armor Set"
