"""This module contains string constants for Clank Challenge locations"""

class RACSMTCLANK:
    """String constants for Clank Challenge locations"""
    METALIS_BRAIN = "Metalis: Clank Challenge: Brain Trip"
    METALIS_GAP = "Metalis: Clank Challenge: Bridge The Gap"
    METALIS_BUZZSAW = "Metalis: Clank Challenge: Buzzsaw Blitz"
    METALIS_CHARGE = "Metalis: Clank Challenge: CHARGE!"
    METALIS_DIVISION = "Metalis: Clank Challenge: Collegiate Division"
    METALIS_BOOGALOO = "Metalis: Clank Challenge: Electric Boogaloo"
    METALIS_LEAGUE = "Metalis: Clank Challenge: Little League"
    METALIS_NIGHT = "Metalis: Clank Challenge: Night Impossible"
    METALIS_TELEPORTERS = "Metalis: Clank Challenge: Of Trapeze and Teleporters"
    METALIS_PROFESSIONAL = "Metalis: Clank Challenge: Professional Level"
    METALIS_SHOWDOWN = "Metalis: Clank Challenge: Showdown"
    METALIS_REVENGE = "Metalis: Clank Challenge: Smasherbot's Revenge"
    METALLIS_TEAM = "Metalis: Clank Challenge: Take Two For The Team"
    METALIS_UBER = "Metalis: Clank Challenge: The Uber Finals"
    METALIS_BRACKET = "Metalis: Clank Challenge: Varsity Bracket"
    DAYNI_MOON_AROUND = "Dayni Moon: Clank Challenge: A-rooouund the Bend"
    DAYNI_MOON_BRIDGE = "Dayni Moon: Clank Challenge: Emergency Bridge"
    DAYNI_MOON_INFINITE = "Dayni Moon: Clank Challenge: Infinite Improbability"
    DAYNI_MOON_LEAP = "Dayni Moon: Clank Challenge: Leap Of Faith"
    DAYNI_MOON_REVERSE = "Dayni Moon: Clank Challenge: Reverse Into Victory"
    DAYNI_MOON_ROUND = "Dayni Moon: Clank Challenge: Round Up!"
    DAYNI_MOON_SMASHER = "Dayni Moon: Clank Challenge: Smasherbot Returns!"
    DAYNI_MOON_LINE = "Dayni Moon: Clank Challenge: The Thin Bouncy Line"
    DAYNI_MOON_SHOWDOWN = "Dayni Moon: Clank Challenge: The Ultimate Showdown"
    DAYNI_MOON_SAWYER = "Dayni Moon: Clank Challenge: Tom Sawyer"
    DAYNI_MOON_TOURNAMENT = "Dayni Moon: Clank Challenge: Tri-bomb Tournament"
    DAYNI_MOON_CROWD = "Dayni Moon: Clank Challenge: Two's A Crowd"
    DAYNI_MOON_VARIETY = "Dayni Moon: Clank Challenge: Variety Is Shocking"
    DAYNI_MOON_WELCOME = "Dayni Moon: Clank Challenge: Welcome to Dayni"
    DAYNI_MOON_HAY = "Dayni Moon: Clank Challenge: HAY-re We Are!"
