"""This module contains string constants used for items"""

class RACSMITEM:
    """String constants for each item"""
    LACERATOR = "Lacerator"
    CONCUSSION_GUN = "Concussion Gun"
    ACID_BOMB_GLOVE = "Acid Bomb Glove"
    AGENTS_OF_DOOM = "Agents of Doom"
    BEE_MINE_GLOVE = "Bee Mine Glove"
    STATIC_BARRIER = "Static Barrier"
    SHOCK_ROCKET = "Shock Rocket"
    SNIPER_MINE = "Sniper Mine"
    SCORCHER = "Scorcher"
    LASER_TRACER = "Laser Tracer"
    SUCK_CANNON = "Suck Cannon"
    MOOTATOR = "Mootator"
    RYNO = "RYNO"

    HYPERSHOT = "Hypershot"
    SPROUT_O_MATIC = "Sprout-O-Matic"
    POLARIZER = "Polarizer"
    PDA = "PDA"
    SHRINK_RAY = "Shrink Ray"
    BOLT_GRABBER = "Bolt Grabber"
    MAP_O_MATIC = "Map-O-Matic"
    BOX_BREAKER = "Box Breaker"

    WILDFIRE_CHESTPLATE = "Wildfire Chestplate"
    WILDFIRE_HELMET = "Wildfire Helmet"
    WILDFIRE_GLOVES = "Wildfire Gloves"
    WILDFIFE_BOOTS = "Wildfire Boots"
    SLUDGE_MK9_CHESTPLATE = "Sludge Mk9 Chestplate"
    SLUDGE_MK9_HELMET = "Sludge Mk9 Helmet"
    SLUDGE_MK9_GLOVES = "Sludge Mk9 Gloves"
    SLUDGE_MK9_BOOTS = "Sludge Mk9 Boots"
    CRYSTALLIX_CHESTPLATE = "Crystallix Chestplate"
    CRYSTALLIX_HELMET = "Crystallix Helmet"
    CRYSTALLIX_GLOVES = "Crystallix Gloves"
    CRYSTALLIX_BOOTS = "Crystallix Boots"
    ELECTROSHOCK_CHESTPLATE = "Electroshock Chestplate"
    ELECTROSHOCK_HELMET = "Electroshock Helmet"
    ELECTROSHOCK_GLOVES = "Electroshock Gloves"
    ELECTROSHOCK_BOOTS = "Electroshock Boots"
    MEGA_BOMB_CHESTPLATE = "Mega Bomb Chestplate"
    MEGA_BOMB_HELMET ="Mega Bomb Helmet"
    MEGA_BOMB_GLOVES ="Mega Bomb Gloves"
    MEGA_BOMB_BOOTS ="Mega Bomb Boots"
    HYPERBOREAN_CHESTPLATE = "Hyperborean Chestplate"
    HYPERBOREAN_HELMET = "Hyperborean Helmet"
    HYPERBOREAN_GLOVES = "Hyperborean Gloves"
    HYPERBOREAN_BOOTS = "Hyperborean Boots"
    CHAMELEON_CHESTPLATE = "Chameleon Chestplate"
    CHAMELEON_HELMET = "Chameleon Helmet"
    CHAMELEON_GLOVES = "Chameleon Gloves"
    CHAMELEON_BOOTS = "Chameleon Boots"

    PROGRESSIVE_LACERATOR = "Progressive Lacerator"
    PROGRESSIVE_CONCUSSION_GUN = "Progressive Concussion Gun"
    PROGRESSIVE_ACID_BOMB_GLOVE = "Progressive Acid Bomb Glove"
    PROGRESSIVE_AGENTS_OF_DOOM = "Progressive Agents of Doom"
    PROGRESSIVE_BEE_MINE_GLOVE = "Progressive Bee Mine Glove"
    PROGRESSIVE_STATIC_BARRIER = "Progressive Static Barrier"
    PROGRESSIVE_SHOCK_ROCKET = "Progressive Shock Rocket"
    PROGRESSIVE_SNIPER_MINE = "Progressive Sniper Mine"
    PROGRESSIVE_SCORCHER = "Progressive Scorcher"
    PROGRESSIVE_LASER_TRACER = "Progressive Laser Tracer"
    PROGRESSIVE_SUCK_CANNON = "Progressive Suck Cannon"
    PROGRESSIVE_MOOTATOR = "Progressive Mootator"
    PROGRESSIVE_RYNO = "Progressive RYNO"

    PROGRESSIVE_LACERATOR_MOD = "Progressive Lacerator Mod"
    PROGRESSIVE_CONCUSSION_GUN_MOD = "Progressive Concussion Gun Mod"
    PROGRESSIVE_ACID_BOMB_GLOVE_MOD = "Progressive Acid Bomb Glove Mod"
    PROGRESSIVE_AGENTS_OF_DOOM_MOD = "Progressive Agents of Doom Mod"
    PROGRESSIVE_BEE_MINE_GLOVE_MOD = "Progressive Bee Mine Glove Mod"
    PROGRESSIVE_STATIC_BARRIER_MOD = "Progressive Static Barrier Mod"
    PROGRESSIVE_SHOCK_ROCKET_MOD = "Progressive Shock Rocket Mod"
    PROGRESSIVE_SNIPER_MINE_MOD = "Progressive Sniper Mine Mod"
    PROGRESSIVE_SCORCHER_MOD = "Progressive Scorcher Mod"
    PROGRESSIVE_LASER_TRACER_MOD = "Progressive Laser Tracer Mod"

    # Individual numbered mod items used when Progressive Mods is off.
    LACERATOR_MOD_LOCK_ON = "Lacerator: Lock On Mod"
    LACERATOR_MOD_DOUBLE_BARREL = "Lacerator: Double Barrel Mod"
    CONCUSSION_GUN_MOD_SPLIT_BARREL = "Concussion Gun: Split Barrel Mod"
    CONCUSSION_GUN_MOD_LOCK_ON = "Concussion Gun: Lock On Mod"
    CONCUSSION_GUN_MOD_CHARGE_UP = "Concussion Gun: Charge Up Mod"
    ACID_BOMB_GLOVE_MOD_ACID_BOMB = "Acid Bomb Glove: Acid Bomb Mod"
    ACID_BOMB_GLOVE_MOD_EPOXY = "Acid Bomb Glove: Epoxy Mod"
    AGENTS_OF_DOOM_MOD_LAUNCHER = "Agents of Doom: Launcher Mod"
    AGENTS_OF_DOOM_MOD_EXPLOSIVE = "Agents of Doom: Explosive Mod"
    BEE_MINE_GLOVE_MOD_WORKER = "Bee Mine Glove: Worker Mod"
    BEE_MINE_GLOVE_MOD_HIVE_BOMB = "Bee Mine Glove: Hive Bomb Mod"
    STATIC_BARRIER_MOD_REFLECTION = "Static Barrier: Reflection Mod"
    STATIC_BARRIER_MOD_MIRAGE = "Static Barrier: Mirage Mod"
    SHOCK_ROCKET_MOD_LOCK_ON = "Shock Rocket: Lock On Mod"
    SHOCK_ROCKET_MOD_AFTER_SHOCK = "Shock Rocket: After Shock Mod"
    SHOCK_ROCKET_MOD_MULTI_LAUNCHER = "Shock Rocket: Multi Launcher Mod"
    SNIPER_MINE_MOD_SPLIT_BEAM = "Sniper Mine: Split Beam Mod"
    SNIPER_MINE_MOD_SMART_REFLECTOR = "Sniper Mine: Smart Reflector Mod"
    SCORCHER_MOD_SPLIT_FIRE = "Scorcher: Split Fire Mod"
    SCORCHER_MOD_SUNFLARE = "Scorcher: Sunflare Mod"
    LASER_TRACER_MOD_PIERCE = "Laser Tracer: Pierce Mod"
    LASER_TRACER_MOD_RICOCHET = "Laser Tracer: Ricochet Mod"

    PROGRESSIVE_WILDFIRE = "Progressive Wildfire Armor"
    PROGRESSIVE_SLUDGE_MK9 ="Progressive Sludge Mk9 Armor"
    PROGRESSIVE_CRYSTALLIX = "Progressive Crystallix Armor"
    PROGRESSIVE_ELECTROSHOCK = "Progressive Electroshock Armor"
    PROGRESSIVE_MEGA_BOMB = "Progressive Mega Bomb Armor"
    PROGRESSIVE_HYPERBOREAN = "Progressive Hyperborean Armor"
    PROGRESSIVE_CHAMELEON = "Progressive Chameleon Armor"

    POKITARU = "Infobot: Pokitaru"
    RYLLUS = "Infobot: Ryllus"
    KALIDON = "Infobot: Kalidon"
    METALIS = "Infobot: Metalis"
    OUTPOST_OMEGA = "Infobot: Outpost Omega"
    CHALLAX = "Infobot: Challax"
    DAYNI_MOON = "Infobot: Dayni Moon"
    QUODRONA = "Infobot: Quodrona"

    BOLTS = "Bolts"
